services:
  postgres:
    image: postgres:latest
    container_name: job-pulse-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_pulse_root # This remains the master/default database
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount initialization script folder below
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: job-pulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: