packages:
  # Name your root-level apps explicitly instead of using "*"
  - "API Gateway"

  # Keep scanning all your nested microservices
  - "Services/*"

allowBuilds:
  "@parcel/watcher": false
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: false
  msgpackr-extract: false
  prisma: true
  unrs-resolver: false
  workerd: false
